### ISSUE TITLE
autopwn issue

### ISSUE THREAD

**Issue by TheUnable** [rpranshu/EternalView#6]
I have a problem with eternalview

*when using the script and choosing 11.Autopwn autopwn seems like its missing from the folder, here is the code error output*
What would you like to do? 11
Make sure that Autopwn is in the same folder
chmod: cannot access 'Autopwn.sh': No such file or directory
./EternalView.sh: line 8866: ./Autopwn.sh: No such file or directory

*I tried entering eternalview.sh to see if i can fix it myself but it seems you hidden the code*

**Comment by rpranshu** [comment]
Autopwn is another tool!

Download it from my repo, on my profile and keep autopwn and eternalview in the same directory!

**Comment by TheUnable** [comment]
Its working fine now, I wish I knew how to code like u :) i added
eternalview and autopwn to my custom os because its an awesome script :)

**Comment by rpranshu** [comment]
I am glad you liked it :)

**Comment by rpranshu** [comment]
I am glad you liked it :)

**Comment by rpranshu** [comment]
For beginners, https://youtu.be/hwrnmQumtPw

Amazing video by Derek banas

After that The Linux Shell - 2016 - Tutorials: https://www.youtube.com/playlist?list=PLcUid3OP_4OV46dBG6R2AvV_-QyB61WRH
